/**
 * A Project Log is an individual piece of log data generated by the User's external application and stored within our database.
 */

import mongoose from "mongoose";

const projectLogsSchema = new mongoose.Schema({
    log: {
        type: String,
        required: true
    },
    secretKeyId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "SecretKey",
        required: true
    },
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },
    isError: {
        type: Boolean,
        default: false
    }
}, { timestamps: true });

export const ProjectLogs = mongoose.models.ProjectLogs || mongoose.model("ProjectLogs", projectLogsSchema, "projectLogs");
